[package]
name = "syno-photo-frame"
version = "0.12.1"
edition = "2021"
description = "Full-screen slideshow for Synology Photos albums"
license = "GPL-3.0-or-later"
authors = ["Piotr Karasinski"]
readme = "README.md"
repository = "https://github.com/caleb9/syno-photo-frame"
keywords = [
    "synology",
    "synology-photos",
    "digital-photo-frame",
    "slideshow",
    "raspberry-pi",
]
rust-version = "1.74"
exclude = [
    ".*",
    "doc/",
    "Dockerfile",
    "dpkg/",
    "assets/*.xcf"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.*"
clap = { version = "4.*", features = ["derive", "wrap_help"] }
ftp = "3.0.1"
image = { version = "0.25.*", default-features = false, features = ["jpeg", "png"] }
lazy-regex = "3.1.0"
log = "0.4.*"
rand = "0.9.*"
sdl2 = "0.37.*"
serde = { version = "1.*", features = ["derive"] }
serde_json = "1.*"
simple_logger = "5.*"
url-parse = "1.0.7"

[dev-dependencies]
mock_instant = "0.5.*"
mockall = "0.13.*"


[target.'aarch64-unknown-linux-gnu'.dependencies]
rppal = "0.22.1"
