[package]
name = "syno-photo-frame"
version = "0.12.1"
edition = "2021"
description = "Full-screen slideshow for Synology Photos albums"
license = "GPL-3.0-or-later"
authors = ["Piotr Karasinski"]
readme = "README.md"
repository = "https://github.com/caleb9/syno-photo-frame"
keywords = [
    "synology",
    "synology-photos",
    "digital-photo-frame",
    "slideshow",
    "raspberry-pi",
]
rust-version = "1.74"
exclude = [
    ".*",
    "doc/",
    "Dockerfile",
    "dpkg/",
    "assets/*.xcf"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.*"
clap = { version = "4.*", features = ["derive", "wrap_help"] }
image = { version = "0.24.*", default-features = false, features = ["jpeg", "png"] }
log = "0.4.*"
rand = "0.8.*"
regex = "1.*"
reqwest = { version = "0.11.*", features = ["blocking", "cookies", "json"] }
sdl2 = "0.36.*"
serde = { version = "1.*", features = ["derive"] }
serde_json = "1.*"
simple_logger = "4.*"

[dev-dependencies]
mock_instant = "0.3.*"
mockall = "0.12.*"
